spring:
  application:
    name: tracking-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/courier_tracking}
      auto-index-creation: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
